CREATE TABLE `User` (
  `id` bigint(20) NOT NULL,
  `screenName` varchar(512) CHARACTER SET utf8 NOT NULL,
  `name` varchar(512) NOT NULL,
  `province` int(11) DEFAULT NULL,
  `city` int(11) DEFAULT NULL,
  `location` varchar(128) DEFAULT NULL,
  `description` varchar(10240) DEFAULT NULL,
  `url` varchar(1024) DEFAULT NULL,
  `profileImageUrl` varchar(1024) DEFAULT NULL,
  `userDomain` varchar(1024) DEFAULT NULL,
  `gender` char(1) DEFAULT 'm',
  `followersCount` int(11) DEFAULT '0',
  `friendsCount` int(11) DEFAULT '0',
  `statusesCount` int(11) DEFAULT NULL,
  `favouritesCount` int(11) DEFAULT NULL,
  `createdAt` datetime DEFAULT NULL,
  `following` varchar(8) DEFAULT '1',
  `verified` varchar(8) DEFAULT '0',
  `verifiedType` int(11) DEFAULT NULL,
  `allowAllActMsg` varchar(8) DEFAULT NULL,
  `allowAllComment` varchar(8) DEFAULT NULL,
  `followMe` varchar(8) DEFAULT NULL,
  `avatarLarge` varchar(1024) DEFAULT NULL,
  `onlineStatus` smallint(6) DEFAULT NULL,
  `statusId` bigint(20) DEFAULT '0',
  `biFollowersCount` int(11) DEFAULT '0',
  `remark` varchar(1024) DEFAULT NULL,
  `lang` varchar(64) DEFAULT NULL,
  `verifiedReason` varchar(1014) DEFAULT NULL,
  `weihao` varchar(1024) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin
